Декоративные элементы
htmlacademy-htmlcss/2286079-sedona-36 pull request #8
Opened 2023-03-05 17:20 UTC by Natyyys

2023-03-07 05:23 UTC, nikopol-fw requested changes

2023-03-07 05:23 UTC, nikopol-fw commented on styles/styles.css
> +}
Этому элементу не нужен `position: absolute;` чек-бокс и текст просто стоят в ряд

2023-03-07 05:23 UTC, nikopol-fw commented on styles/styles.css
> +}
Зачем сразу и before и after?

2023-03-07 05:23 UTC, nikopol-fw commented on styles/styles.css
> +}
Фокус не работает. Его нужно делать через связку input:focus + label, потому что именно input ловит фокус, а не label. Но как вариант, чтобы сильно не переделывать можно попробовать через label:focus-within — только нужно точно понимать, что внутри label будет только один интерактивный элемент — input

2023-03-07 05:23 UTC, nikopol-fw commented on styles/styles.css
> +}
На макете точно есть стили для active? Стилизовать нажатие на поля ввода смысла не видно

2023-03-07 05:23 UTC, nikopol-fw commented on styles/styles.css
> +}
```css
font-family: inherit;
font-weight: 400;
```
Ничего не меняют

2023-03-07 05:23 UTC, nikopol-fw commented on styles/styles.css
> +}
`transform: translate(-35px, 10px);` следует убрать и заменить на координаты. Вообще использовать position: absolute без указания минимум одной координаты по вертикали и горизонтально потенциально ненадежно, так как браузер сам определит положение элемента на основе потока

2023-03-07 05:23 UTC, nikopol-fw commented on styles/styles.css
> +  position: absolute;
position: relative для этих span'ов должны быть их label, а не общий родитель. Подписи "от" и "до" нужно привязать жестко к полям ввода

2023-03-08 11:59 UTC, Natyyys commented on styles/styles.css
> +}
Есть "Текст введён,  курсор внутри поля" и у него черная рамка 2px.

2023-03-09 10:54 UTC, nikopol-fw approved these changes

2023-03-09 10:54 UTC, merged